name: 'dbt_ravenstack'
version: '1.0.0'

profile: 'dbt_ravenstack'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_ravenstack:
    +schema: raw
vars:
  dbt_date:time_zone: "UTC" # Or your local timezone
  dbt_date:week_start_day: 1 # 1 = Monday, 0 = Sunday
  
models:
  dbt_ravenstack:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    reports:
      +materialized: table
      +schema: reports
